Update check_dependency_updates.yaml

diff --git a/.github/workflows/check_dependency_updates.yaml b/.github/workflows/check_dependency_updates.yaml
--- a/.github/workflows/check_dependency_updates.yaml
+++ b/.github/workflows/check_dependency_updates.yaml
@@ -86,7 +86,7 @@ jobs:
       - name: Run ESLint - Linting
         if: always()
         working-directory: ./frontend
-        run: echo "ESLint check failed." >> error_log.txt
+        run: eslint . || echo "ESLint check failed." >> error_log.txt
 
       # MARK: Errors and Issue
 
